/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe with database, Redis and queue checks */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/moments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a moment (validation demo — persistence in E04) */
        post: operations["MomentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a phone OTP
         * @description Issues a 6-digit OTP (5-min validity, 5/hour/phone). Outside production the OTP is returned in `devOtp` for on-screen display during dev testing; production sends via MSG91.
         */
        post: operations["OtpController_request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify OTP and receive a dev session token (7-day expiry) */
        post: operations["OtpController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in / sign up with Google
         * @description Verifies the Google ID token, links the provider account by verified email (no duplicate accounts), blocks under-18 and suspended accounts, and issues a token pair.
         */
        post: operations["SocialController_google"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in / sign up with Apple
         * @description Verifies the Apple identity token against Apple's JWKS, links by email when present, blocks under-18 and suspended accounts, and issues a token pair.
         */
        post: operations["SocialController_apple"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token
         * @description Exchanges a refresh token for a fresh access + refresh pair. The presented token is invalidated; presenting an already-rotated token revokes the whole session (reuse detection).
         */
        post: operations["SessionsController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Deletes the session server-side; the refresh token stops working immediately. Idempotent.
         */
        post: operations["SessionsController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "ok" | "degraded" | "down";
                        version?: string;
                        uptimeSeconds?: number;
                        checks?: {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
    };
    MomentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Sunset chai at Marine Drive */
                    title: string;
                    /** @enum {string} */
                    type?: "hangout" | "event" | "trip" | "celebration" | "activity";
                    /** @enum {string} */
                    privacy?: "public" | "invite_only" | "private";
                };
            };
        };
        responses: {
            /** @description Validated moment payload */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        received?: boolean;
                        moment?: Record<string, never>;
                        /** Format: date-time */
                        receivedAt?: string;
                    };
                };
            };
            /** @description VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RATE_LIMITED */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OtpController_request: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example +919876543210 */
                    phone: string;
                };
            };
        };
        responses: {
            /** @description OTP issued (devOtp present in dev mode) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        requestId?: string;
                        phone?: string;
                        /** @enum {string} */
                        channel?: "dev_screen" | "sms" | "whatsapp";
                        expiresInSeconds?: number;
                        devOtp?: string | null;
                    };
                };
            };
            /** @description VALIDATION_ERROR | OTP_RATE_LIMITED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OtpController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example +919876543210 */
                    phone: string;
                    /** @example 123456 */
                    code: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token?: string;
                        phone?: string;
                        /** Format: date-time */
                        expiresAt?: string;
                    };
                };
            };
            /** @description OTP_INVALID | OTP_EXPIRED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OTP_WRONG | OTP_LOCKED | TOKEN_INVALID */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SocialController_google: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    idToken: string;
                    deviceName?: string;
                };
            };
        };
        responses: {
            /** @description Token pair; isNewUser=true flags first-time users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user?: {
                            id?: string;
                            handle?: string;
                            displayName?: string;
                            email?: string | null;
                            avatarUrl?: string | null;
                        };
                        isNewUser?: boolean;
                        accessToken?: string;
                        /** Format: date-time */
                        accessTokenExpiresAt?: string;
                        refreshToken?: string;
                        /** Format: date-time */
                        refreshTokenExpiresAt?: string;
                    };
                };
            };
            /** @description INVALID_ID_TOKEN | EMAIL_NOT_VERIFIED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNDERAGE_BLOCK | ACCOUNT_SUSPENDED | ACCOUNT_DELETED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SocialController_apple: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    idToken: string;
                    deviceName?: string;
                };
            };
        };
        responses: {
            /** @description Token pair; isNewUser=true flags first-time users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user?: {
                            id?: string;
                            handle?: string;
                            displayName?: string;
                            email?: string | null;
                            avatarUrl?: string | null;
                        };
                        isNewUser?: boolean;
                        accessToken?: string;
                        /** Format: date-time */
                        accessTokenExpiresAt?: string;
                        refreshToken?: string;
                        /** Format: date-time */
                        refreshTokenExpiresAt?: string;
                    };
                };
            };
            /** @description INVALID_ID_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNDERAGE_BLOCK | ACCOUNT_SUSPENDED | ACCOUNT_DELETED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                    deviceName?: string;
                };
            };
        };
        responses: {
            /** @description New token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken?: string;
                        /** Format: date-time */
                        accessTokenExpiresAt?: string;
                        refreshToken?: string;
                        /** Format: date-time */
                        refreshTokenExpiresAt?: string;
                        sessionId?: string;
                    };
                };
            };
            /** @description TOKEN_INVALID | TOKEN_EXPIRED | REFRESH_REUSE_DETECTED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ACCOUNT_SUSPENDED | ACCOUNT_DELETED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revoked?: boolean;
                    };
                };
            };
        };
    };
}
